### 個別設定 ###
# クロージャ内の行数制限
closure_body_length:
- 100 # warning
- 200 # error
# 1ファイルの行数制限
file_length:
- 300   # warning
- 400  # error
# メソッドの行数制限
function_body_length:
- 100 # warning
- 200 # error
# 1行の文字数制限
line_length:
- 200 # warning
- 300 # error
# 型の行数制限
type_body_length:
- 200 # warning
- 300 # error
### Lint対象から除外 ###
excluded:
- Pods/
- Carthage/
- vendor/
- ExitManagementSystemDemo-iOSTests
- ExitManagementSystemDemo-iOSUITests
### 無効にするルール ###
disabled_rules:
- cyclomatic_complexity
- discarded_notification_center_observer
- discouraged_direct_init
- force_cast
- force_try
- function_parameter_count
- identifier_name
- implicit_getter
- multiple_closures_with_trailing_closure
- no_fallthrough_only
- nesting
- type_name
- operator_whitespace
### 有効にするルール ###
opt_in_rules:
- anyobject_protocol
- attributes
- closure_end_indentation
- closure_spacing
- collection_alignment
- convenience_type
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- first_where
- legacy_random
- literal_expression_end_indentation
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- operator_usage_whitespace
- private_action
- private_outlet
- redundant_nil_coalescing
- redundant_type_annotation
- toggle_bool
# - trailing_closure
- unavailable_function
- unused_private_declaration
- vertical_parameter_alignment_on_call
